name: Automatisation des tests DevSecOps

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Dependances:
    name: Contrôle des dépendances
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Trivy
        uses: aquasecurity/setup-trivy@v0.2.3
        with:
          version: latest

      - name: Analyser les dépendances Python
        run: |
          trivy fs \
            --scanners vuln \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            --format table \
            .

  Dockerfile:
    name: Contrôle du Dockerfile
    runs-on: ubuntu-latest
    needs: Dependances
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Trivy
        uses: aquasecurity/setup-trivy@v0.2.3
        with:
          version: latest

      - name: Analyser le Dockerfile
        run: |
          trivy config \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            Dockerfile

  Deploy:
    name: Validation avant déploiement
    runs-on: ubuntu-latest
    needs: Dockerfile
    steps:
      - name: Application prête
        run: echo "Votre application est prête à être déployée"
